### ISSUE TITLE
Better OS/arch support for ML libraries

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31549]
Many ML libraries are notoriously difficult to build on certain platforms. This task tracks known compilation issues for each library.

### PyTorch

- [x] OpenMP segfault on Apple M1 (https://github.com/pytorch/pytorch/issues/80805)
- [x] ROCm support on Cray (https://github.com/pytorch/pytorch/issues/63083)
- [x] PPC64le + RHEL + GCC (https://github.com/spack/spack/issues/28367)
- [ ] asmjit build failure (https://github.com/spack/spack/pull/30985)

### TensorFlow

- [x] Multiple build issues on M1 (https://github.com/tensorflow/tensorflow/issues/56799)
- [x] Enable ROCm support (https://github.com/spack/spack/pull/31380)
- [ ] Protobuf not found (https://github.com/spack/spack/issues/31229)
- [ ] RHEL build issue (https://github.com/spack/spack/issues/29292)
- [ ] GCC 11 support (https://github.com/spack/spack/issues/24378)
- [x] Intel + CentOS build issue (https://github.com/spack/spack/issues/20696)
- [x] Power9 build hangs (https://github.com/spack/spack/issues/20513)

### TensorBoard

- [ ] Native build fails on Apple M1 (https://github.com/tensorflow/tensorboard/issues/5714)

### Bazel

- [ ] Unknown build issue (https://github.com/spack/spack/issues/28925)
- [x] Unknown build issue (https://github.com/spack/spack/issues/21190)
- [x] GCC 11 support (https://github.com/spack/spack/pull/28548)
- [ ] Java version issue (https://github.com/spack/spack/issues/28807)
- [x] Server crash during startup (https://github.com/bazelbuild/bazel/issues/14584)
- [x] aarch64 build failure (https://github.com/bazelbuild/bazel/issues/13554)
- [x] Unknown build issue (https://github.com/bazelbuild/bazel/issues/14536)
- [x] Detection of isystem and Spack toolchain (https://github.com/bazelbuild/bazel/issues/10437)

### Horovod

These are all the same issue, the vendored copy of eigen does not support aarch64 and needs to be updated or patched.

- [x] Eigen build failure on aarch64 (https://github.com/spack/spack/pull/29310)
- [x] Eigen build failure on aarch64 (https://github.com/horovod/horovod/issues/3605)
- [x] Eigen build failure on Apple M1 (https://github.com/horovod/horovod/issues/3587)
- [x] pip install eigen broken on Apple M1 (https://github.com/horovod/horovod/issues/3579)
- [x] horovod uses torch.utils.ffi which was removed (https://github.com/horovod/horovod/issues/3606)
