### ISSUE TITLE
New ML library packages/versions

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31550]
This task tracks new ML libraries (or new versions) that should be added to Spack.

- [x] Horovod 0.22–0.25 (#29310)
- [x] TensorFlow 2.7.1–2.9.1
- [ ] Torchvision C++ libraries (https://github.com/pytorch/pytorch/issues/71359)
- [ ] DL4J
- [x] JAX (https://github.com/spack/spack/pull/27849)
- [ ] Paddle Paddle
- [ ] Shogun (https://github.com/shogun-toolbox/shogun)
- [ ] WEKA
- [ ] Spark MLLib
