### ISSUE TITLE
Better build system support for ML libraries 

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31554]
Many ML libraries including TensorFlow and PyTorch are notoriously difficult to build. We should find ways to improve this.

### Air-gapped networks

Many build systems like Bazel will download dependencies during the installation process. We should find ways to disable this and force the build to use Spack-installed dependencies

- [ ] TensorFlow
- [ ] PyTorch

### Git submodules

Many ML libraries rely on git submodules to manage their dependencies. While this may be convenient for developers, it becomes a nightmare for package maintainers:

1. You have to patch build issues in packages and in all other packages that include them as a submodule
2. Packages often rely on very specific commits of dependencies instead of stable releases
3. A package could end up in the DAG multiple times without ABI compatibility

When possible, we should encourage developers to support externally installed dependencies. Issues I've encountered so far:

- [x] https://github.com/pytorch/pytorch/issues/60329  
- [x] https://github.com/pytorch/pytorch/issues/60334  
- [x] https://github.com/pytorch/pytorch/issues/60332 
- [x] https://github.com/pytorch/pytorch/issues/60270
- [x] https://github.com/pytorch/pytorch/issues/60331

### Bazel toolchain

Spack uses compiler wrappers that rely on environment variables to manage dependencies. Bazel is a hermetic build system that prevents environment variables from affecting builds. These two are fundamentally incompatible.

To get around this, we've [patched Bazel](https://github.com/spack/spack/blob/v0.18.0/var/spack/repos/builtin/packages/bazel/bazelruleclassprovider-0.25.patch) to support Spack env vars. However, this means that external Bazel packages are not supported. Since Bazel can be difficult to build, supporting externally installed Bazel would be a huge plus.

When we raised this issue with the Bazel developers, [their suggestion](https://github.com/bazelbuild/bazel/issues/10437#issuecomment-580493471) was to add a [toolchain](https://bazel.build/docs/toolchains) for Spack. This requires some knowledge of Bazel, but would be extremely beneficial to us.

**Comment by tbags** [comment]
Hi @adamjstewart while building py-torch, the xnn_pack compiles with armv8.2-a+dotprod, on thunderx2t99 (armv8.1-a), the link fails as the ` Error: selected processor does not support <operation such as fmla>`(`cc1: warning: switch ‘-mcpu=thunderx2t99’ conflicts with ‘-march=armv8.2-a+fp16+dotprod’ switch `), I tried to set env flags like so in the package.py: 

```python
       ....
        enable_or_disable("caffe2", keyword="BUILD")

        env.set("CXX_FLAGS", "-march=armv8.1-a -O3 -mcpu=thunderx2t99")
        env.set("CXXFLAGS", "-march=armv8.1-a -O3 -mcpu=thunderx2t99")
        env.set("CFLAGS", "-march=armv8.1-a -O3 -mcpu=thunderx2t99")
        env.set("XNNPACK_ENABLE_ARM_DOTPROD", "OFF")
        ....
```

I also set XNNPACK_ENABLE_ARM_DOTPROD to off. However, while building XNN, it somehow reset the env variables, do you happen to know where to look at, another option I currently thinking of is to have xnn_pack as a separate spack package, but with my limited knowledge, I don't how to set the `XNNPACK_INCLUDE_DIR` to map the spack loaded package. 

could you please point me to how I could resolve this?

**Comment by adamjstewart** [comment]
There's a `USE_SYSTEM_XNNPACK` env var in the `py-torch` package that's commented out that you can play with. Last I tried I got stuck on https://github.com/pytorch/pytorch/issues/60332. Hopefully you can get further than I did.

**Comment by tbags** [comment]
thanks Adam, noob question: if we just said `USE_SYSTEM_XNNPACK`, we'd also need to specify `XNNPACK_INCLUDE_DIR` (would it still be set to the path that's in <spack-src>/third_party/XNNPACK/include) and add  `depends_on('xnnpack')`, correct?

**Comment by adamjstewart** [comment]
You would need to use `depends_on("xnnpack")` (see the commented out code for the version reqs) but I don't think you would need to use `XNNPACK_INCLUDE_DIR`, CMake should find that automatically.
