### ISSUE TITLE
Installation issue: deal.II with Trilinos and CUDA

### ISSUE THREAD

**Issue by pcafrica** [LLNL/spack#32278]
### Steps to reproduce the issue

```console
$ spack spec -I dealii+trilinos+cuda
```

### Error message

```console
==> Error: trilinos '+muelu' conflicts with '~tpetra'
```

### Information on your system

```console
* **Spack:** 0.18.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen
* **Concretizer:** clingo
```

### Additional information

I'm trying to compile deal.II with support to Trilinos and CUDA enabled.
Everything built smoothly (since the installation of OpenMPI CUDA-Aware), except that it seems impossible to enable both dependencies.

Some relevant (conflicting?) lines from `package.py`:
```python
# do not require +rol to make concretization of xsdk possible
depends_on('trilinos+amesos+aztec+epetra+ifpack+ml+muelu+sacado', when='+trilinos')
# TODO: temporary disable Tpetra when using CUDA due to
# namespace "Kokkos::Impl" has no member "cuda_abort"
depends_on('trilinos@master+rol~amesos2~ifpack2~intrepid2~kokkos~tpetra~zoltan2', when='+trilinos+cuda')
```

If I manually disable MueLu, Trilinos gets compiled succesfully, but the configuration of deal.II fails to locate it:
```
-- Found EPETRA_CONFIG_H
-- TRILINOS_LIBRARY_ROL::rol not found! The call was:
--     FIND_LIBRARY(TRILINOS_LIBRARY_ROL::rol NAMES ROL::rol HINTS NO_DEFAULT_PATH NO_CMAKE_ENVIRONMENT_PATH NO_CMAKE_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_SYSTEM_PATH NO_CMAKE_FIND_ROOT_PATH)
...
```
and similar messages for all other Trilinos packages (even if `-DTRILINOS_DIR` points to the correct path).

I'm using a GCC 8.5.0 toolchain, installed via Spack itself.

@jppelteret @luca-heltai 

I would be glad to help!
Thanks in advance!

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jppelteret** [comment]
Hi @elauksap,
Thanks for the detailed report. I'm looking into it in #32415. I'm surprised that you see the configuration failure in deal.II, since [ROL is an optional dependency](https://github.com/dealii/dealii/blob/master/cmake/configure/configure_20_trilinos.cmake#L153). I'll attempt to reproduce the error on my side, after which I can try to determine where the problem lies.
