### ISSUE TITLE
Move compiler searching logic to packages

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#39627]
# Summary

As a core developer, I want to move the search logic for compilers from internal custom compiler classes to external support in packages so that the infrastructure will be ready when we'll move compiler from node attributes to dependencies.

# Description

At some point, during the transition to turn compiler into proper dependencies, we'll need to move the custom search logic that now populates `compilers.yaml` to packages. 

This operation can be done simultaneously with other changes, and without affecting users. The idea is to ensure that we have a package for each compiler we currently support, and add `external find` capabilities equivalent to the current search.

Then, we can add a temporary layer that translates the external information in the current `compilers.yaml` format. This layer will be removed as soon as compilers are turned into dependencies.

# Tasks

- [x] #39633
- [x] #40250
- [x] Write detection tests to replace unit-tests for compiler in core
- [x] #39780
- [x] Handle extra environment variables and extra RPATHs
- [x] Generate compiler entries from `packages.yaml`
- [ ] Use `spack external find` to search for compilers

**Comment by tgamblin** [comment]
Needs handling of:

- [ ] Extra env vars
- [ ] extra RPATHs

for externals
